export type JWHErrorCode =
  | 'ENTRY_INVALID_OBJECT'
  | 'ENTRY_INVALID_ISS'
  | 'ENTRY_INVALID_JTI'
  | 'ENTRY_INVALID_NBF'
  | 'ENTRY_INVALID_AFT'
  | 'ENTRY_INVALID_DOC'
  | 'TOKEN_INVALID_COMPACT_JWS'
  | 'TOKEN_INVALID_PROTECTED_HEADER'
  | 'TOKEN_ALG_NONE_FORBIDDEN'
  | 'TOKEN_ALG_KEY_MISMATCH'
  | 'TOKEN_SIGNATURE_VERIFICATION_FAILED'
  | 'STRING_INVALID_JSON_ARRAY'
  | 'STRING_INVALID_SNAPSHOT_TOKEN'
  | 'HISTORY_EMPTY_SNAPSHOT'
  | 'HISTORY_ISSUER_MISMATCH'
  | 'HISTORY_DOC_SCHEMA_MISMATCH'
  | 'HISTORY_DUPLICATE_JTI'
  | 'HISTORY_CONFLICTING_JTI'
  | 'HISTORY_UNORDERED_SNAPSHOT'
  | 'HISTORY_MERGE_EMPTY_INPUT'
  | 'HISTORY_MERGE_ISSUER_MISMATCH'
  | 'HISTORY_MERGE_DOC_SCHEMA_MISMATCH'
  | 'HISTORY_MERGE_CONFLICTING_JTI'
  | 'HISTORY_MERGE_MISSING_TOKEN'
  | 'HISTORY_ROOT_COUNT_INVALID'
  | 'HISTORY_AFT_REFERENCE_MISSING'
  | 'HISTORY_FORK_DETECTED'
  | 'HISTORY_CYCLE_DETECTED'
  | 'HISTORY_CHAIN_REFERENCE_UNRESOLVED'
  | 'HISTORY_CHAIN_DISCONNECTED'
  | 'HISTORY_INSPECT_TIME_INVALID'
  | 'HISTORY_INSPECT_NO_VALID_ENTRY'
  | 'HISTORY_EXTEND_DOC_SCHEMA_MISMATCH'

export class JWHError extends Error {
  readonly code: JWHErrorCode

  constructor(code: JWHErrorCode, message?: string) {
    const detail = message ?? code
    super(`{@z-base/json-web-history} ${detail}`)
    this.code = code
    this.name = 'JWHError'
  }
}
