export { createHistory } from './JWH/createHistory/index.js'
export { mergeHistories } from './JWH/mergeHistories/index.js'
export { updateHistory } from './JWH/updateHistory/index.js'
export { openHistory } from './JWH/openHistory/index.js'
export { findRoot } from './JWH/findRoot/index.js'
export { findHead } from './JWH/findHead/index.js'
